# TODO: Change the name of the org 
org: lamnt63
app: project5-udacity
service: project5-udacity

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-plugin-tracing
  - serverless-aws-documentation
  - serverless-reqvalidator-plugin

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  tracing:
    lambda: true
    apiGateway: true

  # Use these variables in the functions and resouorces section below. For example, 
  # ${self:provider.environment.ATTACHMENT_S3_BUCKET_VALUE}
  environment:
    CARTS_TABLE: Carts-${self:provider.stage}
    CARTS_CREATED_AT_INDEX: CreatedAtIndex
    ATTACHMENT_S3_BUCKET_VALUE: project5-cart-serverless-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300
 
  logs:
    # Enable API Gateway logs
    restApi: true

custom:
  documentation:
    api:
      info:
        version: v1.0.0
        title: Cart API
        description: serverless api
    models:
      - name: CreateCartRequest
        contentType: application/json
        schema: ${file(models/create-cart-model.json)}
      - name: UpdateCartRequest
        contentType: application/json
        schema: ${file(models/update-cart-model.json)}

functions:

  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  # Listask: Configure this function - 
  # Provide iamRoleStatements property for performing Actions on DynamoDB
  GetCarts:
    handler: src/lambda/http/getList.handler
    events:
      - http:
          method: get
          path: carts
          cors: true
          authorizer: Auth
          reqValidatorName: RequestBodyValidatorToDos
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource: arn:aws:s3:::${self:provider.environment.ATTACHMENT_S3_BUCKET_VALUE}/*
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CARTS_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CARTS_TABLE}/index/${self:provider.environment.CARTS_CREATED_AT_INDEX}
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource:
          - "*"

  # Task: Configure this function - 
  # Provide iamRoleStatements property. Decide the Actions and AWS Resource. 
  # To refer to an AWS resource defined in the "Resources" section, you can use "Resource: !GetAtt <resource-name>.Arn"
  # To validate incoming HTTP requests, we have provided the request schemas in function definition below. 
  CreateCart:
    handler: src/lambda/http/create.handler
    events:
      - http:
          method: post
          path: carts
          cors: true
          authorizer: Auth
          reqValidatorName: RequestBodyValidatorToDos
          documentation:
            summary: Create a new item 
            description: Create a new item 
            requestModels:
              'application/json': CreateCartRequest
          request:
            schemas:
              application/json: ${file(models/create-cart-model.json)}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CARTS_TABLE}
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource:
          - "*"

  # Function update item
  UpdateCart:
    handler: src/lambda/http/update.handler
    events:
      - http:
          cors: true
          path: todos/{todoId}
          method: patch
          authorizer: Auth
          reqValidatorName: RequestBodyValidatorToDos
          documentation:
            summary: Update a item 
            description: Update a item
            requestModels:
              'application/json': UpdateCartRequest
          request:
            schemas:
              application/json: ${file(models/update-cart-model.json)}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CARTS_TABLE}
      - Effect: Allow
        Action:
          - xray:PutTelemetryRecords
          - xray:PutTraceSegments
        Resource:
          - "*"

  #Function delete 
  DeleteCart:
    handler: src/lambda/http/delete.handler
    events:
      - http:
          cors: true
          path: todos/{todoId}
          method: delete
          authorizer: Auth
          reqValidatorName: RequestBodyValidatorToDos
          documentation:
            summary: Delete a item 
            description: Delete a item 
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CARTS_TABLE}
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource:
          - "*"

  # TODO: Configure this function
  # Function handle upload images
  UploadUrlImage:
    handler: src/lambda/http/uploadUrlImage.handler
    events:
      - http:
          cors: true
          path: todos/{todoId}/attachment
          method: post
          authorizer: Auth
          reqValidatorName: RequestBodyValidatorToDos
          documentation:
            summary: Upload url image 
            description: Upload url image 
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.CARTS_TABLE}
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource: arn:aws:s3:::${self:provider.environment.ATTACHMENT_S3_BUCKET_VALUE}/*
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource:
          - "*"

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi
    
    # TODO: Create a DynamoDB table
    CartsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: todoId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: todoId
              KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.CARTS_TABLE}
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.CARTS_CREATED_AT_INDEX}
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
                ProjectionType: ALL

    RequestBodyValidatorToDos:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'request-body-validator'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false            

    # TODO: Complete the bucket properties below. 
    # Do not forget to add the CorsConfiguration property
    AttachmentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.ATTACHMENT_S3_BUCKET_VALUE}
        OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false 
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                  - HEAD
                  - GET
                  - POST
                  - PUT
                  - DELETE
              AllowedOrigins:
                - "*"
              MaxAge: 300 

    # TODO: Complete the policy below and attach it to the bucket defined above
    # For cross referencing the name of the bucket, use "!Ref AttachmentsBucket"
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyBucketPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Action: 's3:GetObject'
              Principal: '*'
              Resource: 'arn:aws:s3:::${self:provider.environment.ATTACHMENT_S3_BUCKET_VALUE}/*'
        Bucket: !Ref AttachmentsBucket